name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - 'packages/container/**'

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
        cd /tmp
        unzip awscliv2.zip
        sudo ./aws/install --update
        cd -
      - run: pip3 install awscli_plugin_endpoint && pip3 show awscli_plugin_endpoint
      - run: |
        mkdir ~/.aws
        cp ./aws/config ~/.aws/config
      - run: /usr/local/bin/aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
